code --install-extension aaron-bond.better-comments
code --install-extension AffenWiesel.matlab-formatter
code --install-extension ahmadawais.shades-of-purple
code --install-extension akamud.vscode-theme-onedark
code --install-extension alefragnani.Bookmarks
code --install-extension ArashSahebolamri.alloy
code --install-extension austin.code-gnu-global
code --install-extension batisteo.vscode-django
code --install-extension be5invis.vscode-custom-css
code --install-extension bradlc.vscode-tailwindcss
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension cschlosser.doxdocgen
code --install-extension csstools.postcss
code --install-extension danielpinto8zz6.c-cpp-compile-run
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension DongyuZhao.alloy-vscode
code --install-extension donjayamanne.python-environment-manager
code --install-extension donjayamanne.python-extension-pack
code --install-extension DotJoshJohnson.xml
code --install-extension dracula-theme.theme-dracula
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension eg2.vscode-npm-script
code --install-extension enkia.tokyo-night
code --install-extension esbenp.prettier-vscode
code --install-extension fernandoescolar.vscode-solution-explorer
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension goessner.mdmath
code --install-extension GrapeCity.gc-excelviewer
code --install-extension Gruntfuggly.todo-tree
code --install-extension hediet.vscode-drawio
code --install-extension jchannon.csharpextensions
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension jeff-hykin.better-shellscript-syntax
code --install-extension jmrog.vscode-nuget-package-manager
code --install-extension johnpapa.winteriscoming
code --install-extension KevinRose.vsc-python-indent
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension magicstack.MagicPython
code --install-extension mechatroner.rainbow-csv
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension mtxr.sqltools
code --install-extension mtxr.sqltools-driver-mysql
code --install-extension njpwerner.autodocstring
code --install-extension oderwat.indent-rainbow
code --install-extension patbenatar.advanced-new-file
code --install-extension quicktype.quicktype
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension sdras.night-owl
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension sleistner.vscode-fileutils
code --install-extension somekittens.hot-dog-stand
code --install-extension stevencl.addDocComments
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension stylelint.vscode-stylelint
code --install-extension tomoki1207.pdf
code --install-extension twxs.cmake
code --install-extension usernamehw.errorlens
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wholroyd.jinja
code --install-extension wix.glean
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xUnn4m3DD.vscode-paint
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme
